package segundaEntrega.Presentacion.Empleado;

import javax.swing.JOptionPane;

import segundaEntrega.Negocio.Departamento.Departamento;
import segundaEntrega.Negocio.Empleado.Empleado;
import segundaEntrega.Negocio.Empleado.EmpleadoTiempoCompleto;
import segundaEntrega.Negocio.Empleado.EmpleadoTiempoParcial;
import segundaEntrega.Presentacion.Vista;
import segundaEntrega.Presentacion.Controlador.Evento;
import segundaEntrega.Presentacion.Controlador.Implementacion.ControladorImp;
import segundaEntrega.Presentacion.Empleado.GUIAltaEmpleado;
import segundaEntrega.Presentacion.Dispatcher.EventoVista;

public class GUIAltaEmpleado extends javax.swing.JFrame implements Vista{

	
	static private GUIAltaEmpleado altaEmpleado;

    /**
     * Creates new form GUIAnadirHabitacion
     */
    public GUIAltaEmpleado() {
        initComponents();
    }

    static public GUIAltaEmpleado obtenerInstancia(){
		   if(altaEmpleado == null){
			   altaEmpleado = new GUIAltaEmpleado();
		   }
		   
		   return altaEmpleado;
	  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabelIDNI = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jFormattedTextFieldDNI = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDepartamento= new javax.swing.JFormattedTextField();
        jFormattedTextFieldNombre = new javax.swing.JFormattedTextField();
        jButtonAceptar = new javax.swing.JButton();
        jLabelSalario = new javax.swing.JLabel();
        jLabelDepartamento = new javax.swing.JLabel();
        jFormattedTextFieldSalario = new javax.swing.JFormattedTextField();
        jLabelHoras = new javax.swing.JLabel();
        jLabelAnosTrabajados = new javax.swing.JLabel();
        jFormattedTextFieldPlus = new javax.swing.JFormattedTextField();
        jFormattedTextFieldHoras = new javax.swing.JFormattedTextField();
        jLabelPlus = new javax.swing.JLabel();
        jLabelPrecioHora = new javax.swing.JLabel();
        jFormattedTextFieldAnosTrabajados = new javax.swing.JFormattedTextField();
        jFormattedTextFieldPrecioHora = new javax.swing.JFormattedTextField();
        jRadioButtonTiempoParcial = new javax.swing.JRadioButton();
        jFormattedTextFieldHoras.setEnabled(false);
		jFormattedTextFieldPrecioHora.setEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelIDNI.setText("DNI");

        jLabelNombre.setText("Nombre");

        jLabelDepartamento.setText("Departamento");

        jButtonAceptar.setText("Aceptar");

        jLabelSalario.setText("Salario");

        jLabelHoras.setText("Horas");

        jLabelAnosTrabajados.setText("Años Trabajados");

        jLabelPlus.setText("Plus");

        jLabelPrecioHora.setText("Precio/hora");

        jRadioButtonTiempoParcial.setText("Tiempo Parcial");
        jRadioButtonTiempoParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTiempoParcialActionPerformed(evt);
            }
        });
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jButtonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jButtonAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSalario)
                            .addComponent(jLabelNombre))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelIDNI)
                    .addComponent(jRadioButtonTiempoParcial)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDepartamento)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextFieldDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHoras)
                    .addComponent(jLabelPrecioHora)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelPlus)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFormattedTextFieldPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelAnosTrabajados)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFormattedTextFieldPrecioHora, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFormattedTextFieldAnosTrabajados, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFormattedTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelIDNI)
                            .addComponent(jFormattedTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSalario)
                            .addComponent(jFormattedTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDepartamento)
                            .addComponent(jFormattedTextFieldDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonTiempoParcial)
                        .addGap(34, 34, 34)
                        .addComponent(jButtonAceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAnosTrabajados, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldAnosTrabajados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrecioHora, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldPrecioHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>                        

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {  
	   	 if(jFormattedTextFieldSalario.getText().isEmpty()||jFormattedTextFieldDNI.getText().isEmpty()||jFormattedTextFieldNombre.getText().isEmpty()||jFormattedTextFieldDepartamento.getText().isEmpty()){
	   		JOptionPane.showMessageDialog(null, "ERROR!! Rellene todos los campos", "Nuevo Empleado", JOptionPane.ERROR_MESSAGE); 
	   	 }else{
	   		 
	   		Empleado empleado;
	   		if(jRadioButtonTiempoParcial.isSelected()){
	   		empleado= new EmpleadoTiempoParcial();	
	   		((EmpleadoTiempoParcial)empleado).setHoras(Integer.valueOf(jFormattedTextFieldHoras.getText()));
		   	((EmpleadoTiempoParcial)empleado).setPrecio_hora(Integer.valueOf(jFormattedTextFieldPrecioHora.getText()));
	   			
	   		}else{
		   	empleado= new EmpleadoTiempoCompleto();
		   	((EmpleadoTiempoCompleto)empleado).setPlus(Integer.valueOf(jFormattedTextFieldPlus.getText()));
		   	((EmpleadoTiempoCompleto)empleado).setAnos_trabajados(Integer.valueOf(jFormattedTextFieldAnosTrabajados.getText()));

	   		}
	  	   empleado.setNombre(jFormattedTextFieldNombre.getText());
	  	   empleado.setSalario(Integer.valueOf(jFormattedTextFieldSalario.getText()));  
	  	   empleado.setDni(jFormattedTextFieldDNI.getText());
	  	   Departamento d = new Departamento();
	  	   d.setNombre(jFormattedTextFieldDepartamento.getText());
	  	   empleado.setDepartamento(d);
	  	   
	         ControladorImp.getInstancia().execute(Evento.ALTA_EMPLEADO, empleado);
	   	 }
	        // TODO add your handling code here:
	    }                                           

    private void jRadioButtonTiempoParcialActionPerformed(java.awt.event.ActionEvent evt) {   
    	
    	if ( this.jRadioButtonTiempoParcial.isSelected()){
    		jFormattedTextFieldPlus.setEnabled(false);
    		jFormattedTextFieldAnosTrabajados.setEnabled(false);
    		jFormattedTextFieldHoras.setEnabled(true);
    		jFormattedTextFieldPrecioHora.setEnabled(true);
    	}else{
    		jFormattedTextFieldHoras.setEnabled(false);
    		jFormattedTextFieldPrecioHora.setEnabled(false);
    		jFormattedTextFieldPlus.setEnabled(true);
    		jFormattedTextFieldAnosTrabajados.setEnabled(true);
    	}
        // TODO add your handling code here:
    }                                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAltaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAltaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAltaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAltaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAltaEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JFormattedTextField jFormattedTextFieldAnosTrabajados;
    private javax.swing.JFormattedTextField jFormattedTextFieldDNI;
    private javax.swing.JFormattedTextField jFormattedTextFieldDepartamento;
    private javax.swing.JFormattedTextField jFormattedTextFieldHoras;
    private javax.swing.JFormattedTextField jFormattedTextFieldNombre;
    private javax.swing.JFormattedTextField jFormattedTextFieldPlus;
    private javax.swing.JFormattedTextField jFormattedTextFieldPrecioHora;
    private javax.swing.JFormattedTextField jFormattedTextFieldSalario;
    private javax.swing.JLabel jLabelAnosTrabajados;
    private javax.swing.JLabel jLabelDepartamento;
    private javax.swing.JLabel jLabelHoras;
    private javax.swing.JLabel jLabelIDNI;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPlus;
    private javax.swing.JLabel jLabelPrecioHora;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JRadioButton jRadioButtonTiempoParcial;
    // End of variables declaration                   
	@Override
	public void actualizar(int id_evento_vista, Object datos) {
		
		

		jFormattedTextFieldAnosTrabajados.setText("");
		jFormattedTextFieldDNI.setText("");
		jFormattedTextFieldHoras.setText("");
		jFormattedTextFieldNombre.setText("");
		jFormattedTextFieldPlus.setText("");
		jFormattedTextFieldPrecioHora.setText("");
		jFormattedTextFieldSalario.setText("");
		jFormattedTextFieldDepartamento.setText("");
		jRadioButtonTiempoParcial.setSelected(false);
		
		if(id_evento_vista == EventoVista.ALTA_EMPLEADO_EXITO){
			JOptionPane.showMessageDialog(null, "Se ha creado el Empleado con exito con ID:  " + (int)datos,"Nuevo Empleado", JOptionPane.INFORMATION_MESSAGE);		
		}	
	
		else if (id_evento_vista == EventoVista.ALTA_EMPLEADO_FALLO){
			JOptionPane.showMessageDialog(null, "ERROR!! Ha ocurrido un error", "Nuevo Empleado", JOptionPane.ERROR_MESSAGE);
		}
		
		
		
		
	}
}

