package segundaEntrega.Presentacion.Empleado;

import javax.swing.JOptionPane;

import segundaEntrega.Negocio.Empleado.ClavesEmpleadoTarea;
import segundaEntrega.Negocio.Empleado.Empleado;
import segundaEntrega.Negocio.Empleado.EmpleadoTarea;
import segundaEntrega.Negocio.Empleado.EmpleadoTiempoParcial;
import segundaEntrega.Negocio.Tarea.Tarea;
import segundaEntrega.Presentacion.Vista;
import segundaEntrega.Presentacion.Controlador.Evento;
import segundaEntrega.Presentacion.Controlador.Implementacion.ControladorImp;
import segundaEntrega.Presentacion.Dispatcher.EventoVista;

public class GUIAsignarEmpleadoTarea extends javax.swing.JFrame implements Vista {

	static private GUIAsignarEmpleadoTarea asignarEmpleadoTarea;
    /**
     * Creates new form GUIAltaHabitacion
     */
    public GUIAsignarEmpleadoTarea() {
        initComponents();
    }
    
    static public GUIAsignarEmpleadoTarea obtenerInstancia(){
		   if(asignarEmpleadoTarea == null){
			   asignarEmpleadoTarea = new GUIAsignarEmpleadoTarea();
		   }
		   
		   return asignarEmpleadoTarea;
	  }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabelIDEmpleado = new javax.swing.JLabel();
        jFormattedTextFieldIDEmpleado = new javax.swing.JFormattedTextField();
        jButtonAceptar = new javax.swing.JButton();
        jLabelIDTarea = new javax.swing.JLabel();
        jLabelNumHoras  = new javax.swing.JLabel();
        jFormattedTextFieldNumHoras = new javax.swing.JFormattedTextField();
        jFormattedTextFieldIDTarea = new javax.swing.JFormattedTextField();
        

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelIDEmpleado.setText("Id empleado");

        jButtonAceptar.setText("Aceptar");

        jLabelIDTarea.setText("Id Tarea");
        jLabelNumHoras.setText("Num Horas");
        
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jButtonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jButtonAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIDEmpleado)
                    .addComponent(jLabelIDTarea)
                    .addComponent(jLabelNumHoras))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextFieldNumHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldIDTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldIDEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldIDEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIDEmpleado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFormattedTextFieldIDTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIDTarea))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumHoras)
                    .addComponent(jFormattedTextFieldNumHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButtonAceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    
    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {  
	   	 if(jFormattedTextFieldIDEmpleado.getText().isEmpty()&&jFormattedTextFieldIDTarea.getText().isEmpty()){
	   		JOptionPane.showMessageDialog(null, "ERROR!! Rellene todos los campos", "Asignar Empleado Tarea", JOptionPane.ERROR_MESSAGE); 
	   	 }else{
	   		 
	   		
	   		 //da igual el tipo de empleado, solo es para transportar su id;
	   		 EmpleadoTarea et = new EmpleadoTarea();
	   		 ClavesEmpleadoTarea clavesEmpleadoTarea = new ClavesEmpleadoTarea(Integer.valueOf(jFormattedTextFieldIDEmpleado.getText()),Integer.valueOf(jFormattedTextFieldIDTarea.getText()));
	   		et.setClaves(clavesEmpleadoTarea);	
	   		et.setNumHorasTarea(Integer.valueOf(jFormattedTextFieldNumHoras.getText()));
	  	   
	         ControladorImp.getInstancia().execute(Evento.ASIGNAR_TAREA,et);
	   	 }
	        // TODO add your handling code here:
	    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAsignarEmpleadoTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAsignarEmpleadoTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAsignarEmpleadoTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAsignarEmpleadoTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAsignarEmpleadoTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JFormattedTextField jFormattedTextFieldIDEmpleado;
    private javax.swing.JFormattedTextField jFormattedTextFieldIDTarea;
    private javax.swing.JFormattedTextField jFormattedTextFieldNumHoras;
    private javax.swing.JLabel jLabelIDEmpleado;
    private javax.swing.JLabel jLabelIDTarea;
    private javax.swing.JLabel jLabelNumHoras;
    // End of variables declaration                   
	@Override
	public void actualizar(int id_evento_vista, Object datos) {
		//Borra lo anterior
    	
		jFormattedTextFieldIDEmpleado.setText("");
		jFormattedTextFieldIDTarea.setText("");
        
		
		if(id_evento_vista == EventoVista.ASIGNAR_TAREA_EXITO){
			JOptionPane.showMessageDialog(null, "Se ha asignado con exito la tarea con id " + (int)datos + " al empleado", "Asignar Tarea", JOptionPane.INFORMATION_MESSAGE);
	   }
	   else if(id_evento_vista == EventoVista.ASIGNAR_TAREA_FALLO_EMPLEADO_NO_EXISTE){
			JOptionPane.showMessageDialog(null, "ERROR!! El empleado no existe", "Asignar Tarea", JOptionPane.ERROR_MESSAGE);
	   }
	   else if(id_evento_vista == EventoVista.ASIGNAR_TAREA_FALLO_TAREA_NO_EXISTE){
		   JOptionPane.showMessageDialog(null, "ERROR!! La tarea no existe", "Asignar Tarea", JOptionPane.ERROR_MESSAGE);
	   }
	   else if(id_evento_vista == EventoVista.ASIGNAR_TAREA_FALLO_TAREA_YA_ASIGNADA_EMPLEADO){
		   JOptionPane.showMessageDialog(null, "ERROR!! La tarea ya está asignada al empleado", "Asignar Tarea", JOptionPane.ERROR_MESSAGE);
	   }
	   else if(id_evento_vista == EventoVista.ASIGNAR_TAREA_FALLO_EMPLEADO_YA_ASIGNADO_TAREA){
		   JOptionPane.showMessageDialog(null, "ERROR!! El empleado ya está asignado a la tarea", "Asignar Tarea", JOptionPane.ERROR_MESSAGE);
	   }
	   
		
	}
}
