package segundaEntrega.Presentacion.Empleado;

import javax.swing.JOptionPane;

import segundaEntrega.Negocio.Empleado.ClavesEmpleadoTarea;
import segundaEntrega.Negocio.Empleado.Empleado;
import segundaEntrega.Negocio.Empleado.EmpleadoTiempoParcial;
import segundaEntrega.Negocio.Tarea.Tarea;
import segundaEntrega.Presentacion.Vista;
import segundaEntrega.Presentacion.Controlador.Evento;
import segundaEntrega.Presentacion.Controlador.Implementacion.ControladorImp;
import segundaEntrega.Presentacion.Dispatcher.EventoVista;

public class GUIEliminarEmpleadoTarea extends javax.swing.JFrame implements Vista {

	static private GUIEliminarEmpleadoTarea eliminarEmpleadoTarea;
    /**
     * Creates new form GUIAltaHabitacion
     */
    public GUIEliminarEmpleadoTarea() {
        initComponents();
    }
    
    static public GUIEliminarEmpleadoTarea obtenerInstancia(){
		   if(eliminarEmpleadoTarea == null){
			   eliminarEmpleadoTarea = new GUIEliminarEmpleadoTarea();
		   }
		   
		   return eliminarEmpleadoTarea;
	  }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabelIDEmpleado = new javax.swing.JLabel();
        jFormattedTextFieldIDEmpleado = new javax.swing.JFormattedTextField();
        jButtonAceptar = new javax.swing.JButton();
        jLabelIDTarea = new javax.swing.JLabel();
        jFormattedTextFieldIDTarea = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelIDEmpleado.setText("Id empleado");

        jButtonAceptar.setText("Aceptar");

        jLabelIDTarea.setText("Id Tarea");
        
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jButtonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jButtonAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabelIDTarea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelIDEmpleado)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextFieldIDTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldIDEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldIDEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIDEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIDTarea)
                    .addComponent(jFormattedTextFieldIDTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jButtonAceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    
    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {  
	   	 if(jFormattedTextFieldIDEmpleado.getText().isEmpty()&&jFormattedTextFieldIDTarea.getText().isEmpty()){
	   		JOptionPane.showMessageDialog(null, "ERROR!! Rellene todos los campos", "Eliminar Empleado Tarea", JOptionPane.ERROR_MESSAGE); 
	   	 }else{
	   		 
	   		 ClavesEmpleadoTarea clavesEmpleadoTarea = new ClavesEmpleadoTarea(Integer.valueOf(jFormattedTextFieldIDEmpleado.getText()),Integer.valueOf(jFormattedTextFieldIDTarea.getText()));
	  	   
	         ControladorImp.getInstancia().execute(Evento.ELIMINAR_TAREA,clavesEmpleadoTarea);
	   	 }
	        // TODO add your handling code here:
	    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEliminarEmpleadoTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEliminarEmpleadoTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEliminarEmpleadoTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEliminarEmpleadoTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIEliminarEmpleadoTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JFormattedTextField jFormattedTextFieldIDEmpleado;
    private javax.swing.JFormattedTextField jFormattedTextFieldIDTarea;
    private javax.swing.JLabel jLabelIDEmpleado;
    private javax.swing.JLabel jLabelIDTarea;
    // End of variables declaration                   
	@Override
	public void actualizar(int id_evento_vista, Object datos) {
		//Borra lo anterior
    	
		jFormattedTextFieldIDEmpleado.setText("");
		jFormattedTextFieldIDTarea.setText("");
        
		
		if(id_evento_vista == EventoVista.ELIMINAR_TAREA_EXITO){
			JOptionPane.showMessageDialog(null, "Se ha eliminado con exito la tarea con id  del empleado", "Eliminar Tarea", JOptionPane.INFORMATION_MESSAGE);
	   }else if(id_evento_vista == EventoVista.ELIMINAR_TAREA_FALLO){
			JOptionPane.showMessageDialog(null, "ERROR!! no se ha eliminado la tarea", "Eliminar Tarea", JOptionPane.ERROR_MESSAGE);
	   }
	   
		
	}
}