package segundaEntrega.Presentacion.Empleado;

import javax.swing.JOptionPane;

import segundaEntrega.Negocio.Departamento.Departamento;
import segundaEntrega.Negocio.Empleado.Empleado;
import segundaEntrega.Negocio.Empleado.EmpleadoTarea;
import segundaEntrega.Negocio.Empleado.EmpleadoTiempoCompleto;
import segundaEntrega.Negocio.Empleado.EmpleadoTiempoParcial;
import segundaEntrega.Negocio.Tarea.Tarea;
import segundaEntrega.Presentacion.Vista;
import segundaEntrega.Presentacion.Controlador.Evento;
import segundaEntrega.Presentacion.Controlador.Implementacion.ControladorImp;
import segundaEntrega.Presentacion.Dispatcher.EventoVista;

public class GUIMostrarEmpleado extends javax.swing.JFrame implements Vista {

	
	static private GUIMostrarEmpleado mostrarEmpleado;

    /**
     * Creates new form GUIAnadirHabitacion
     */
    public GUIMostrarEmpleado() {
        initComponents();
    }
    
    static public GUIMostrarEmpleado obtenerInstancia(){
		   if(mostrarEmpleado == null){
			   mostrarEmpleado = new GUIMostrarEmpleado();
		   }
		   
		   return mostrarEmpleado;
	  }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabelIDNI = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jFormattedTextFieldDNI = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDNI.setEditable(false);
        jFormattedTextFieldNombre = new javax.swing.JFormattedTextField();
        jFormattedTextFieldNombre.setEditable(false);
        jButtonAceptar = new javax.swing.JButton();
        jLabelSalario = new javax.swing.JLabel();
        jFormattedTextFieldSalario = new javax.swing.JFormattedTextField();
        jFormattedTextFieldSalario.setEditable(false);
        jLabelHoras = new javax.swing.JLabel();
        jLabelAnosTrabajados = new javax.swing.JLabel();
        jFormattedTextFieldPlus = new javax.swing.JFormattedTextField();
        jFormattedTextFieldPlus.setEditable(false);
        jFormattedTextFieldHoras = new javax.swing.JFormattedTextField();
        jFormattedTextFieldHoras.setEditable(false);
        jLabelPlus = new javax.swing.JLabel();
        jLabelPrecioHora = new javax.swing.JLabel();
        jFormattedTextFieldAnosTrabajados = new javax.swing.JFormattedTextField();
        jFormattedTextFieldAnosTrabajados.setEditable(false);
        jFormattedTextFieldPrecioHora = new javax.swing.JFormattedTextField();
        jFormattedTextFieldPrecioHora.setEditable(false);
        jRadioButtonTiempoParcial = new javax.swing.JRadioButton();
        jRadioButtonTiempoParcial.setEnabled(false);
        jLabelDepartamento = new javax.swing.JLabel();
        jFormattedTextFieldDepartamento = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDepartamento.setEditable(false);
        jLabelID = new javax.swing.JLabel();
        jFormattedTextFieldID = new javax.swing.JFormattedTextField();
        jScrollPaneTareas = new javax.swing.JScrollPane();
        jTextAreaTareas = new javax.swing.JTextArea();
        jTextAreaTareas.setEditable(false);
        jLabelTareas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelIDNI.setText("DNI");

        jLabelNombre.setText("Nombre");

       

        jButtonAceptar.setText("Aceptar");

        jLabelSalario.setText("Salario");

        jLabelHoras.setText("Horas");

        jLabelAnosTrabajados.setText("Años Trabajados");

        jLabelPlus.setText("Plus");

        jLabelPrecioHora.setText("Precio/hora");

        jRadioButtonTiempoParcial.setText("Tiempo Parcial");
       

        jLabelDepartamento.setText("Departamento");

        jLabelID.setText("ID");

        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jButtonAceptarActionPerformed(evt);
            }
        });

        jTextAreaTareas.setColumns(20);
        jTextAreaTareas.setRows(5);
        jScrollPaneTareas.setViewportView(jTextAreaTareas);

        jLabelTareas.setText("Tareas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFormattedTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelSalario)
                                            .addComponent(jLabelNombre))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jFormattedTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jFormattedTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jFormattedTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabelIDNI)
                                    .addComponent(jRadioButtonTiempoParcial)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelDepartamento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFormattedTextFieldDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jButtonAceptar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(jLabelID)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelHoras)
                            .addComponent(jLabelPrecioHora)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelPlus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jFormattedTextFieldPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelAnosTrabajados)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextFieldPrecioHora, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldAnosTrabajados, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPaneTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabelTareas))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID)
                    .addComponent(jFormattedTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelIDNI)
                            .addComponent(jFormattedTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSalario)
                            .addComponent(jFormattedTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDepartamento)
                            .addComponent(jFormattedTextFieldDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAnosTrabajados, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldAnosTrabajados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrecioHora, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldPrecioHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonTiempoParcial)
                        .addGap(62, 62, 62)
                        .addComponent(jButtonAceptar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabelTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPaneTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        this.addWindowListener(new java.awt.event.WindowAdapter() {
			@Override
			public void windowClosing(java.awt.event.WindowEvent windowEvent) {
				// Borra lo anterior
				jFormattedTextFieldAnosTrabajados.setText("");
			     jFormattedTextFieldDNI.setText("");
			     jFormattedTextFieldDepartamento.setText("");
			     jFormattedTextFieldHoras.setText("");
			     jFormattedTextFieldID.setText("");
			     jFormattedTextFieldNombre.setText("");
			     jFormattedTextFieldPlus.setText("");
			     jFormattedTextFieldPrecioHora.setText("");
			     jFormattedTextFieldSalario.setText("");
			     jTextAreaTareas.setText("");

			}
		});
        pack();
    }// </editor-fold>                        

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {  
	   	 if(jFormattedTextFieldID.getText().isEmpty()){
	   		JOptionPane.showMessageDialog(null, "ERROR!! Rellene todos los campos", "Mostrar Empleado", JOptionPane.ERROR_MESSAGE); 
	   	 }else{
	   		 
	         ControladorImp.getInstancia().execute(Evento.MOSTRAR_EMPLEADO, Integer.valueOf(jFormattedTextFieldID.getText()));
	   	 }
	        // TODO add your handling code here:
	    }                                                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMostrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMostrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMostrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMostrarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMostrarEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JFormattedTextField jFormattedTextFieldAnosTrabajados;
    private javax.swing.JFormattedTextField jFormattedTextFieldDNI;
    private javax.swing.JFormattedTextField jFormattedTextFieldDepartamento;
    private javax.swing.JFormattedTextField jFormattedTextFieldHoras;
    private javax.swing.JFormattedTextField jFormattedTextFieldID;
    private javax.swing.JFormattedTextField jFormattedTextFieldNombre;
    private javax.swing.JFormattedTextField jFormattedTextFieldPlus;
    private javax.swing.JFormattedTextField jFormattedTextFieldPrecioHora;
    private javax.swing.JFormattedTextField jFormattedTextFieldSalario;
    private javax.swing.JLabel jLabelAnosTrabajados;
    private javax.swing.JLabel jLabelDepartamento;
    private javax.swing.JLabel jLabelHoras;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelIDNI;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPlus;
    private javax.swing.JLabel jLabelPrecioHora;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JLabel jLabelTareas;
    private javax.swing.JRadioButton jRadioButtonTiempoParcial;
    private javax.swing.JScrollPane jScrollPaneTareas;
    private javax.swing.JTextArea jTextAreaTareas;
    // End of variables declaration                   
	@Override
	public void actualizar(int id_evento_vista, Object datos) {
		   		 
		   		
		   	 
		   	 jFormattedTextFieldAnosTrabajados.setText("");
		     jFormattedTextFieldDNI.setText("");
		     jFormattedTextFieldDepartamento.setText("");
		     jFormattedTextFieldHoras.setText("");
		     jFormattedTextFieldNombre.setText("");
		     jFormattedTextFieldPlus.setText("");
		     jFormattedTextFieldPrecioHora.setText("");
		     jFormattedTextFieldSalario.setText("");
		     jTextAreaTareas.setText("");
				
		         if(id_evento_vista == EventoVista.MOSTRAR_EMPLEADO_EXITO){
		        	 
		     		
				     if (datos.getClass().equals(EmpleadoTiempoCompleto.class)){
				    	 EmpleadoTiempoCompleto e = (EmpleadoTiempoCompleto)datos;
				    	 jFormattedTextFieldAnosTrabajados.setText(Integer.toString(e.getAnos_trabajados()));
					     jFormattedTextFieldPlus.setText(Integer.toString(e.getPlus()));
					     jFormattedTextFieldDNI.setText(e.getDni());
					     jFormattedTextFieldDepartamento.setText(e.getDepartamento().getNombre());
					     jFormattedTextFieldNombre.setText(e.getNombre());
					     jFormattedTextFieldSalario.setText(Integer.toString(e.getSalario()));
					     
					     jTextAreaTareas.append("ID\n\n");
							
							for(EmpleadoTarea t: e.getLista_tareas()){
								jTextAreaTareas.append(Integer.toString(t.getClaves().getIdTarea())+ "\n"); 
							}
				    	 
				    	 
				     }else{
				    	 EmpleadoTiempoParcial e = (EmpleadoTiempoParcial)datos; 
				    	 jFormattedTextFieldPrecioHora.setText(Integer.toString(e.getPrecio_hora()));
					     jFormattedTextFieldHoras.setText(Integer.toString(e.getHoras()));
					     jFormattedTextFieldDNI.setText(e.getDni());
					     jFormattedTextFieldDepartamento.setText(e.getDepartamento().getNombre());
					     jFormattedTextFieldNombre.setText(e.getNombre());
					     jFormattedTextFieldSalario.setText(Integer.toString(e.getSalario()));
					     
					     jTextAreaTareas.append("ID\tNOMBRE \n\n");
							
					     for(EmpleadoTarea t: e.getLista_tareas()){
								jTextAreaTareas.append(Integer.toString(t.getClaves().getIdTarea())+ "\n"); 
							}
				    	 
				     }
				     	
				  
		     		
		     	}
		 		else if(id_evento_vista == EventoVista.MOSTRAR_EMPLEADO_FALLO){
		 			JOptionPane.showMessageDialog(null, "ERROR!! No se ha encontrado el empleado que se desea mostrar", "Mostrar Empleado", JOptionPane.ERROR_MESSAGE);
		 		}
				
		   	 
		        // TODO add your handling code here:
		
	}
}
