package segundaEntrega.Presentacion.Departamento;

import javax.swing.JOptionPane;

import segundaEntrega.Negocio.Departamento.Departamento;
import segundaEntrega.Negocio.Empleado.Empleado;
import segundaEntrega.Negocio.Transfer.TransferCliente;
import segundaEntrega.Negocio.Transfer.TransferClienteStandar;
import segundaEntrega.Negocio.Transfer.TransferClienteVip;
import segundaEntrega.Presentacion.Vista;
import segundaEntrega.Presentacion.Controlador.Evento;
import segundaEntrega.Presentacion.Controlador.Implementacion.ControladorImp;
import segundaEntrega.Presentacion.Dispatcher.EventoVista;

public class GUIMostrarDepartamento extends javax.swing.JFrame implements Vista {

	static private GUIMostrarDepartamento mostrarDepartamento;
	
    /**
     * Creates new form GUIAltaHabitacion
     */
    public GUIMostrarDepartamento() {
        initComponents();
    }
    
    /**
	   * Obtiene la instancia de la ventana
	   * @return la instancia de la ventana
	   */
	  static public GUIMostrarDepartamento obtenerInstancia(){
		   if(mostrarDepartamento == null){
			   mostrarDepartamento = new GUIMostrarDepartamento();
		   }
		   
		   return mostrarDepartamento;
	  }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabelActividad = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jFormattedTextFieldNombre = new javax.swing.JFormattedTextField();
        jFormattedTextFieldNombre.setEditable(false);;
        jButtonAceptar = new javax.swing.JButton();
        jFormattedTextFieldActividad = new javax.swing.JFormattedTextField();
        jFormattedTextFieldActividad.setEditable(false);
        jLabelID = new javax.swing.JLabel();
        jFormattedTextFieldID = new javax.swing.JFormattedTextField();
        jScrollPanelEmpleados = new javax.swing.JScrollPane();
        jTextAreaEmpleados = new javax.swing.JTextArea();
        jTextAreaEmpleados.setEditable(false);
        jLabelActividad1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelActividad.setText("Actividad");

        jLabelNombre.setText("Nombre");

        jButtonAceptar.setText("Aceptar");

        jLabelID.setText("Id");

        jTextAreaEmpleados.setColumns(20);
        jTextAreaEmpleados.setRows(5);
        jScrollPanelEmpleados.setViewportView(jTextAreaEmpleados);

        jLabelActividad1.setText("Empleados:");
        
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jButtonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabelID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jFormattedTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jFormattedTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelActividad)
                                .addGap(44, 44, 44)
                                .addComponent(jFormattedTextFieldActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabelActividad1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPanelEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jButtonAceptar)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelID)
                    .addComponent(jFormattedTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelActividad)
                    .addComponent(jFormattedTextFieldActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelActividad1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPanelEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAceptar)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
			@Override
			public void windowClosing(java.awt.event.WindowEvent windowEvent) {
        jFormattedTextFieldNombre.setText("");
		jFormattedTextFieldActividad.setText("");
        jTextAreaEmpleados.setText("");

			}
		});
        pack();
    }// </editor-fold>                        

    
    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {  
	   	 if(jFormattedTextFieldID.getText().isEmpty()){
	   		JOptionPane.showMessageDialog(null, "ERROR!! Rellene todos los campos", "Mostrar Departamento", JOptionPane.ERROR_MESSAGE); 
	   	 }else{
	   		 
	  	 
	  	   
	         ControladorImp.getInstancia().execute(Evento.MOSTAR_DEPARTAMENTO,Integer.valueOf(jFormattedTextFieldID.getText()));
	   	 }
	        // TODO add your handling code here:
	    }   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMostrarDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMostrarDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMostrarDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMostrarDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMostrarDepartamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JFormattedTextField jFormattedTextFieldActividad;
    private javax.swing.JFormattedTextField jFormattedTextFieldID;
    private javax.swing.JFormattedTextField jFormattedTextFieldNombre;
    private javax.swing.JLabel jLabelActividad;
    private javax.swing.JLabel jLabelActividad1;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JScrollPane jScrollPanelEmpleados;
    private javax.swing.JTextArea jTextAreaEmpleados;
    // End of variables declaration                   

	@Override
	public void actualizar(int id_evento_vista, Object datos) {
			//Borra lo anterior
	    	
	    	 
			jFormattedTextFieldNombre.setText("");
			jFormattedTextFieldActividad.setText("");
	        jTextAreaEmpleados.setText("");
			
	         if(id_evento_vista == EventoVista.MOSTAR_DEPARTAMENTO_EXITO){
	     		Departamento d = (Departamento) datos;
	     		
	     		jFormattedTextFieldNombre.setText(d.getNombre());
	     		jFormattedTextFieldActividad.setText(d.getActividad());
	     			
	     		
	  
	     	
	 			//IDs de las facturas
	     		//jTextAreaEmpleados.append(" ID Empleados \n\n");
	     		
	 			for(Empleado i: d.getLista_empleados()){
	 				jTextAreaEmpleados.append(" " + i.getId() +" " + i.getNombre() + "\n"); 
	 			}
	     		
	     	}
	 		else if(id_evento_vista == EventoVista.MOSTAR_DEPARTAMENTO_FALLO){
	 			JOptionPane.showMessageDialog(null, "ERROR!! No se ha encontrado el departamento que se desea mostrar", "Mostrar Departamento", JOptionPane.ERROR_MESSAGE);
	 		}
			
		}
}
